<?php

namespace AppBundle\Repository;

/**
 * CostItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostItemRepository extends \Doctrine\ORM\EntityRepository
{
}
