<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Extra;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraSnapshotRepository extends SnapshotRepository
{
    public function getCurrent(Extra $extra, int $version){

        return $this->findOneBy(['extra'=>$extra, 'version' => $version]);
    }
}
