<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CostItem;

/**
 * CostItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemSnapshotRepository extends SnapshotRepository
{
    public function getCurrent(CostItem $item, int $version){

        return $this->findOneBy(['costItem'=>$item, 'version' => $version]);
    }
}
