<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ServiceCategory;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return ServiceCategory|null
     */
    public function getDefaultCategory(){

        return $this->findOneBy([], ['id'=>'DESC']);
    }
}
