<?php

namespace AppBundle\Repository;

/**
 * CostItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class SnapshotRepository extends \Doctrine\ORM\EntityRepository
{

}
