sonata_admin:
  title: BWSS
  title_logo: bwss.png
  show_mosaic_button:   false
  options:
    html5_validate: false
  #        lock_protection: true #https://symfony.com/doc/master/bundles/SonataAdminBundle/cookbook/recipe_lock_protection.html

sonata_block:
  default_contexts: [cms]
  blocks:
    # enable the SonataAdminBundle block
    sonata.user.block.menu:
    sonata.user.block.account:
    sonata.block.service.text:
    sonata.admin.block.admin_list:
      contexts:   [admin]
    # ...

sonata_core:
  form:
    mapping:
      enabled: false

services:
  app.admin.service_category:
    class: AppBundle\Admin\ServiceCategoryAdmin
    arguments: [~, AppBundle\Entity\ServiceCategory, AppBundle:ServiceCategoryAdmin]
    tags:
    - { name: sonata.admin, manager_type: orm, group: admin, label: Service Category }
    public: true

  app.admin.service:
    class: AppBundle\Admin\ServiceAdmin
    arguments: [~, AppBundle\Entity\Service, AppBundle:ServiceAdmin]
    tags:
    - { name: sonata.admin, manager_type: orm, group: admin, label: Service }
    public: true

  app.admin.cost_item:
    class: AppBundle\Admin\CostItemAdmin
    arguments: [~, AppBundle\Entity\CostItem, AppBundle:CostItemAdmin]
    tags:
    - { name: sonata.admin, manager_type: orm, group: admin, label: CostItem }
    public: true

  app.admin.offer_item:
    class: AppBundle\Admin\OfferItemAdmin
    arguments: [~, AppBundle\Entity\OfferItem, AppBundle:OfferItemAdmin]
    tags:
    - { name: sonata.admin, manager_type: orm, group: Offers, label: OfferItem }
    public: true

  app.admin.offer:
    class: AppBundle\Admin\OfferAdmin
    arguments: [~, AppBundle\Entity\Offer, AppBundle:OfferAdmin]
    tags:
    - { name: sonata.admin, manager_type: orm, group: Offers, label: Offer }
    public: true

  app.admin.item_snapshot:
    class: AppBundle\Admin\ItemSnapshotAdmin
    arguments: [~, AppBundle\Entity\ItemSnapshot, AppBundle:ItemSnapshotAdmin]
    tags:
    - { name: sonata.admin, manager_type: orm, group: Snapshots, label: CostItem Snapshot }
    public: true

  app.admin.service_snapshot:
    class: AppBundle\Admin\ServiceSnapshotAdmin
    arguments: [~, AppBundle\Entity\ServiceSnapshot, AppBundle:ServiceSnapshotAdmin]
    tags:
    - { name: sonata.admin, manager_type: orm, group: Snapshots, label: Service Snapshot }
    public: true

  app.admin.category_snapshot:
    class: AppBundle\Admin\CategorySnapshotAdmin
    arguments: [~, AppBundle\Entity\CategorySnapshot, AppBundle:CategorySnapshotAdmin]
    tags:
    - { name: sonata.admin, manager_type: orm, group: Snapshots, label: Category Snapshot }
    public: true

#  app.admin.price:
#    class: AppBundle\Admin\PriceAdmin
#    arguments: [~, AppBundle\Entity\Price, AppBundle:PriceAdmin]
#    tags:
#    - { name: sonata.admin, manager_type: orm, group: admin, label: Price }
#    public: true
