hautelook_alice:
  fixtures_path: 'Resources/fixtures/' # Path to which to look for fixtures relative to the project directory or the bundle path.
  root_dirs:
  - '%kernel.root_dir%'
  - '%kernel.project_dir%'

nelmio_alice:
  locale: '%locale%' # Default locale for the Faker Generator
  seed: 12 # Value used make sure Faker generates data consistently across
  # runs, set to null to disable.
  functions_blacklist: # Some Faker formatter may have the same name as PHP
  - 'current'      # native functions. PHP functions have the priority,
    # so if you want to use a Faker formatter instead,
  # blacklist this function here
  loading_limit: 5 # Alice may do some recursion to resolve certain values.
    # This parameter defines a limit which will stop the
  # resolution once reached.
  max_unique_values_retry: 150 # Maximum number of time Alice can try to
    # generate a unique value before stopping and
  # failing.
